name       : geos
version    : 3.8.1
release    : 4
source     :
    - https://github.com/libgeos/geos/archive/3.8.1.tar.gz : 605df3f99056b7bb9c48f20d67e90e539f5a9ca5b2c7896d58ba06e3217dc106
homepage   : https://trac.osgeo.org/geos
license    : LGPL-2.1-only
component  : programming
summary    : GEOS - Geometry Engine, Open Source
description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the JTS Topology Suite (JTS). It includes the OpenGIS Simple Features for SQL spatial predicate functions and spatial operators, as well as specific JTS enhanced topology functions.
libsplit   : false
patterns   :
    - /usr/include/geos*
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
