name       : geos
version    : 3.5.0
release    : 1
source     :
    - http://download.osgeo.org/geos/geos-3.5.0.tar.bz2 : 49982b23bcfa64a53333dab136b82e25354edeb806e5a2e2f5b8aa98b1d0ae02
license    : LGPL-2.1
component  : programming
summary    : GEOS - Geometry Engine, Open Source
description: |
    GEOS - Geometry Engine, Open Source
libsplit   : false
builddeps  :
    - pkgconfig(python-2.7)
setup      : |
    sed -i -e 's|= isnan(|= std::isnan(|g' configure
    sed -i -e 's|(isnan(|(std::isnan(|g' include/geos/platform.h.in
    %configure --disable-static --enable-python
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /usr/include/geos*