name       : geos
version    : 3.6.2
release    : 2
source     :
    - http://download.osgeo.org/geos/geos-3.6.2.tar.bz2 : 045a13df84d605a866602f6020fc6cbf8bf4c42fb50de237a08926e1d7d7652a
license    : LGPL-2.1-only
component  : programming
summary    : GEOS - Geometry Engine, Open Source
description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the JTS Topology Suite (JTS). It includes the OpenGIS Simple Features for SQL spatial predicate functions and spatial operators, as well as specific JTS enhanced topology functions.
libsplit   : false
patterns   :
    - /usr/include/geos*
builddeps  :
    - swig
setup      : |
    sed -i -e 's|= isnan(|= std::isnan(|g' configure
    sed -i -e 's|(isnan(|(std::isnan(|g' include/geos/platform.h.in
    %configure --disable-static --enable-python
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
