name       : geos
version    : 3.10.1
release    : 5
source     :
    - https://github.com/libgeos/geos/archive/refs/tags/3.10.1.tar.gz : 15180d727df60ea2e61ece6273feaa3b2a4554db0a447bf6923054df676c78c0
homepage   : https://trac.osgeo.org/geos
license    : LGPL-2.1-only
component  : programming
summary    : GEOS - Geometry Engine, Open Source
description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the JTS Topology Suite (JTS). It includes the OpenGIS Simple Features for SQL spatial predicate functions and spatial operators, as well as specific JTS enhanced topology functions.
libsplit   : false
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
patterns   :
    - devel :
        - /usr/bin/geos-config
